# Generated by Django 4.2 on 2023-04-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HAsker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='lame_user', max_length=256),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HAsker.profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HAsker.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(-1, 'dislike'), (1, 'like')])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HAsker.profile')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HAsker.tag'),
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HAsker.vote')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAsker.question')),
            ],
            bases=('HAsker.vote',),
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HAsker.vote')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAsker.answer')),
            ],
            bases=('HAsker.vote',),
        ),
    ]
