# Generated by Django 4.2 on 2023-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAsker', '0002_remove_answer_rating_remove_profile_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='HAsker.tag'),
        ),
    ]
