# Generated by Django 4.2 on 2023-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAsker', '0004_alter_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(null=True, to='HAsker.tag'),
        ),
    ]
