# Generated by Django 4.2 on 2023-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAsker', '0007_profile_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervote',
            old_name='answer',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='question',
            new_name='object',
        ),
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('author', 'object')},
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('author', 'object')},
        ),
    ]
